### PR TITLE
Ref #379 adding weibo search topic

### PR DESCRIPTION
**Pull request by Tanych**
Ref https://github.com/gwu-libraries/sfm-ui/issues/379
* supporting Weibo search with topic
* adding Weibo search statues web resource extractor
* adding testing cases for Weibo search and options

To use the Weibo search, the user needs to give authorization to SFM instance in Weibo open platform or get their own advanced `access_token` in Weibo app platform.

To merge this PR, also need to deal with https://github.com/gwu-libraries/sfm-ui/pull/624

### CODE REVIEW

**Comment by kerchner** [comment]
@Tanych It looks like this failed the unit tests - is there something in the unit tests that needs to be fixed?

**Comment by Tanych** [comment]
@kerchner  I will take a look at it.

**Comment by kerchner** [comment]
Fixes https://github.com/gwu-libraries/sfm-ui/issues/379

**Comment by kerchner** [comment]
Fixes gwu-libraries/sfm-ui#379

**Pull request merged**
